from constants import SLACK_PLATFORM

ACTIVATE_TOKEN = "activate"
DEACTIVATE_TOKEN = "deactivate"
COMPLETE_TOKEN = "complete"
MATCH_TOKEN = "match"

LOCATIONS = []

MESSAGING_PLATFORM = SLACK_PLATFORM

SLACK_API_TOKEN = ""
